import { Language } from './LanguageContext';

export const languages: { code: Language; name: string; flag: string }[] = [
  { code: 'ko', name: '한국어', flag: '🇰🇷' },
  { code: 'en', name: 'English', flag: '🇺🇸' },
  { code: 'zh', name: '中文', flag: '🇨🇳' },
  { code: 'ja', name: '日本語', flag: '🇯🇵' },
  { code: 'ru', name: 'Русский', flag: '🇷🇺' },
  { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
  { code: 'ar', name: 'العربية', flag: '🇸🇦' },
  { code: 'es', name: 'Español', flag: '🇪🇸' },
  { code: 'pt-BR', name: 'Português', flag: '🇧🇷' },
  { code: 'id', name: 'Bahasa Indonesia', flag: '🇮🇩' },
  { code: 'af', name: 'Afrikaans', flag: '🇿🇦' },
  { code: 'vi', name: 'Tiếng Việt', flag: '🇻🇳' },
  { code: 'pl', name: 'Polski', flag: '🇵🇱' },
];

export const translations: Record<string, Record<Language, string>> = {
  header_title: {
    ko: 'AI 글로벌 커머스 플랫폼',
    en: 'AI Global Commerce Platform',
    zh: 'AI 全球电子商务平台',
    ja: 'AI グローバルコマースプラットフォーム',
    ru: 'Глобальная платформа ИИ-коммерции',
    hi: 'AI 글로벌 कॉमर्स प्लेटफॉर्म',
    ar: 'منصة التجارة العالمية بالذكاء الاصطناعي',
    es: 'Plataforma de Comercio Global IA',
    'pt-BR': 'Plataforma de Comércio Global IA',
    id: 'Platform Perdagangan Global AI',
    af: 'AI Global Commerce Platform',
    vi: 'Nền tảng Thương mại Toàn cầu AI',
    pl: 'Globalna Platforma Handlowa AI',
  },
  nav_dashboard: { ko: '대시보드', en: 'Dashboard', zh: '仪表板', ja: 'ダッシュボード', ru: 'Панель', hi: 'डैशबोर्ड', ar: 'لوحة القيادة', es: 'Tablero', 'pt-BR': 'Painel', id: 'Dasbor', af: 'Dashboard', vi: 'Bảng điều khiển', pl: 'Pulpit' },
  nav_growth: { ko: '성장 엔진', en: 'Growth Engine', zh: '增长引擎', ja: '成長エンジン', ru: 'Двигатель роста', hi: 'ग्रोथ इंजन', ar: 'محرك النمو', es: 'Motor de Crecimiento', 'pt-BR': 'Motor de Crescimento', id: 'Mesin Pertumbuhan', af: 'Growth Engine', vi: 'Động cơ tăng trưởng', pl: 'Silnik Wzrostu' },
  nav_pim: { ko: '상품 관리', en: 'PIM (Products)', zh: '产品管理', ja: '商品管理', ru: 'Управление товарами', hi: 'उत्पाद प्रबंधन', ar: 'إدارة المنتجات', es: 'Gestión de Productos', 'pt-BR': 'Gestão de Produtos', id: 'Manajemen Produk', af: 'Produkbestuur', vi: 'Quản lý sản phẩm', pl: 'Zarządzanie Produktami' },
  nav_oms: { ko: '주문 관리', en: 'OMS (Orders)', zh: '订单管理', ja: '注文管理', ru: 'Управление заказами', hi: 'आदेश प्रबंधन', ar: 'إدارة الطلبات', es: 'Gestión de Pedidos', 'pt-BR': 'Gestão de Pedidos', id: 'Manajemen Pesanan', af: 'Bestellingsbestuur', vi: 'Quản lý đơn hàng', pl: 'Zarządzanie Zamówieniami' },
  nav_marketplace: { ko: '마켓플레이스', en: 'Marketplace', zh: '市场', ja: 'マーケットプレイス', ru: 'Мар켓плейс', hi: 'मार्켓플레이스', ar: 'السوق', es: 'Mercado', 'pt-BR': 'Marketplace', id: 'Pasar', af: 'Marketplace', vi: 'Chợ', pl: 'Rynek' },
  nav_sourcing: { ko: '상품 소싱', en: 'AI Sourcing', zh: '产品采购', ja: '商品ソーシング', ru: 'Поиск товаров', hi: 'उत्पाद सोर्सिंग', ar: 'مصادر المنتجات', es: 'Búsqueda de Productos', 'pt-BR': 'Sourcing de Produtos', id: 'Sourcing Produk', af: 'Produkverkryging', vi: 'Tìm nguồn hàng', pl: 'Pozyskiwanie Produktów' },
  nav_b2b: { ko: 'B2B 몰', en: 'B2B Private', zh: 'B2B 私人商城', ja: 'B2B プ라이베이트몰', ru: 'B2B-магазин', hi: 'B2B 프라이빗 몰', ar: 'متجر B2B الخاص', es: 'Tienda Privada B2B', 'pt-BR': 'Loja Privada B2B', id: 'Mal Pribadi B2B', af: 'B2B Privaat Mall', vi: 'Trung tâm B2B', pl: 'Prywatny Sklep B2B' },
  
  b2b_welcome: { ko: '승인된 파트너를 위한 독점 가격 및 대량 주문.', en: 'Exclusive pricing and bulk ordering for approved partners.', zh: '为经批准的合作伙伴提供独家定价和大宗订购。', ja: '承認されたパートナー向けの独占価格と大量注文。', ru: 'Эксклюзивные цены и оптовые заказы для проверенных партнеров.', hi: 'अनुमोदित भागीदारों के लिए विशेष मूल्य निर्धारण और थोक आदेश।', ar: 'أسعار حصرية وطلبات بالجملة للشركاء المعتمدين.', es: 'Precios exclusivos y pedidos al por mayor para socios aprobados.', 'pt-BR': 'Preços exclusivos e pedidos em massa para parceiros aprovados.', id: 'Harga eksklusif dan pemesanan massal untuk mitra yang disetujui.', af: 'Eksklusiewe pryse en grootmaatbestelling vir goedgekeurde vennote.', vi: 'Giá độc quyền và đặt hàng số lượng lớn cho các đối tác đã được phê duyệt.', pl: 'Ekskluzywne ceny i zamówienia hurtowe dla zatwierdzonych partnerów.' },
  b2b_tier: { ko: '현재 등급', en: 'Current Tier', zh: '当前等级', ja: '現在のティア', ru: 'Текущий уровень', hi: 'वर्तमान स्तर', ar: 'المستوى الحالي', es: 'Nivel Actual', 'pt-BR': 'Nível Atual', id: 'Tingkat Saat Ini', af: 'Huidige Vlak', vi: 'Cấp độ hiện tại', pl: 'Bieżący Poziom' },
  b2b_upgrade: { ko: '등급 업그레이드', en: 'Upgrade Tier', zh: '升级等级', ja: 'ティアをアップグレード', ru: 'Повысить уровень', hi: 'स्तर अपग्रेड करें', ar: 'ترقية المستوى', es: 'Mejorar Nivel', 'pt-BR': 'Atualizar Nível', id: 'Tingkatkan Tingkat', af: 'Gradeer Vlak op', vi: 'Nâng cấp cấp độ', pl: 'Ulepsz Poziom' },
  b2b_moq: { ko: '최소 주문 수량', en: 'MOQ', zh: '最小起订量', ja: '最小注文数量', ru: 'Мин. заказ', hi: 'न्यूनतम आदेश मात्रा', ar: 'أقل كمية ممكن طلبها', es: 'Pedido Mínimo', 'pt-BR': 'Quantidade Mínima de Pedido', id: 'MOQ', af: 'MOQ', vi: 'Số lượng tối thiểu', pl: 'Minimalna Ilość Zamówienia' },
  b2b_bulk_order: { ko: '대량 주문', en: 'Bulk Order', zh: '大宗订单', ja: '大量注文', ru: 'Оптовый заказ', hi: 'थोक आदेश', ar: 'طلب بالجملة', es: 'Pedido al por Mayor', 'pt-BR': 'Pedido em Massa', id: 'Pesanan Massal', af: 'Grootmaatbestelling', vi: 'Đặt hàng số lượng lớn', pl: 'Zamówienie Hurtowe' },
  b2b_reseller_api: { ko: '리셀러 API', en: 'Reseller API', zh: '分销商 API', ja: '리세러API', ru: 'API для реселлеров', hi: 'पुनर्विक्रेता API', ar: 'واجهة برمجة تطبيقات الموزع', es: 'API de Revendedor', 'pt-BR': 'API de Revendedor', id: 'API Reseller', af: 'Herverkoper-API', vi: 'API đại lý', pl: 'API dla Odsprzedawców' },
  b2b_reseller_api_desc: { ko: 'REST API를 통해 상점을 재고에 직접 연결하십시오.', en: 'Connect your store directly to our inventory via REST API.', zh: '通过 REST API 将您的商店直接连接到我们的库存。', ja: 'REST API를介해서 ストアを在庫に直接接続します。', ru: 'Подключите свой магазин напрямую к нашему инвентарю через REST API.', hi: 'REST API के माध्यम से अपने स्टोर को सीधे हमारी इन्वेंट्री से जोड़ें।', ar: 'قم بتوصيل متجرك مباشرة بمخزوننا عبر واجهة برمجة تطبيقات REST.', es: 'Conecte su tienda directamente a nuestro inventario a través de la API REST.', 'pt-BR': 'Conecte sua loja diretamente ao nosso inventário via API REST.', id: 'Hubungkan toko Anda langsung ke inventaris kami melalui REST API.', af: 'Koppel jou winkel direk aan ons voorraad via REST API.', vi: 'Kết nối cửa hàng của bạn trực tiếp với kho hàng của chúng tôi thông qua REST API.', pl: 'Połącz swój sklep bezpośrednio z naszymi zapasami za pomocą interfejsu REST API.' },
  b2b_credit_line: { ko: '신용 한도', en: 'Credit Line', zh: '信用额度', ja: '信用枠', ru: 'Кредитная линия', hi: 'कредиट लाइन', ar: 'خط الائتمان', es: 'Línea de Crédito', 'pt-BR': 'Linha de Crédito', id: 'Lini Kredit', af: 'Kredietlyn', vi: 'Hạn mức tín dụng', pl: 'Linia Kredytowa' },
  b2b_credit_line_desc: { ko: 'net-30 기준으로 주문 결제를 위한 신용 한도를 신청하십시오.', en: 'Apply for a credit line to pay for orders on a net-30 basis.', zh: '申请信用额度以在 net-30 基础上支付订单。', ja: 'net-30ベースで注文を支払うための信用枠を申請してください。', ru: 'Подайте заявку на кредитную линию для оплаты заказов на условиях net-30.', hi: 'नेट-30 आधार पर ऑर्डर के भुगतान के लिए क्रेडिट लाइन के लिए आवेदन करें।', ar: 'تقدم بطلب للحصول على خط ائتمان لدفع ثمن الطلبات على أساس صافي 30.', es: 'Solicite una línea de crédito para pagar pedidos en una base neta de 30.', 'pt-BR': 'Solicite uma linha de crédito para pagar pedidos em uma base líquida de 30.', id: 'Ajukan lini kredit untuk membayar pesanan berdasarkan net-30.', af: 'Doen aansoek vir \'n kredietlyn om vir bestellings op \'n netto-30 basis te betaal.', vi: 'Đăng ký hạn mức tín dụng để thanh toán cho các đơn hàng trên cơ sở net-30.', pl: 'Złóż wniosek o linię kredytową, aby płacić za zamówienia w terminie 30 dni.' },
  b2b_white_label: { ko: '화이트 라벨', en: 'White Label', zh: '白标', ja: 'ホワイトラベル', ru: 'White Label', hi: 'व्हा이트 लेबल', ar: 'العلامة البيضاء', es: 'Marca Blanca', 'pt-BR': 'Marca Branca', id: 'Label Putih', af: 'Wit Etiket', vi: 'Nhãn trắng', pl: 'White Label' },
  b2b_white_label_desc: { ko: '대량 주문 시 맞춤형 포장 및 브랜딩이 가능합니다.', en: 'Custom packaging and branding available for bulk orders.', zh: '大宗订单可提供定制包装和品牌。', ja: '大量注文の場合、カスタムパッケージとブランディングが利用可能です.', ru: 'Для оптовых заказов доступна индивидуальная упаковка и брендинг.', hi: 'थोक आदेशों के लिए उपलब्ध कस्टम पैकेजिंग और ब्रांडिंग।', ar: 'تتوفر التعبئة والتغليف المخصصة والعلامات التجارية للطلبات بالجملة.', es: 'Embalaje y marca personalizados disponibles para pedidos al por mayor.', 'pt-BR': 'Embalagem e marca personalizadas disponíveis para pedidos em massa.', id: 'Kemasan dan branding khusus tersedia untuk pesanan massal.', af: 'Pasgemaakte verpakking en handelsmerk beskikbaar vir grootmaatbestellings.', vi: 'Bao bì và thương hiệu tùy chỉnh có sẵn cho các đơn hàng số lượng lớn.', pl: 'Dla zamówień hurtowych dostępne są niestandardowe opakowania i branding.' },

  pim_add_product: { ko: '상품 추가', en: 'Add Product', zh: '添加产品', ja: '商品を追加', ru: 'Добавить товар', hi: 'उत्पाद जोड़ें', ar: 'إضافة منتج', es: 'Añadir Producto', 'pt-BR': 'Adicionar Produto', id: 'Tambah Produk', af: 'Voeg Produk by', vi: 'Thêm sản phẩm', pl: 'Dodaj Produkt' },
  pim_search: { ko: '상품 검색...', en: 'Search products...', zh: '搜索产品...', ja: '商品を検索...', ru: 'Поиск товаров...', hi: 'उत्पाद खोजें...', ar: 'بحث عن المنتجات...', es: 'Buscar productos...', 'pt-BR': 'Pesquisar produtos...', id: 'Cari produk...', af: 'Soek produkte...', vi: 'Tìm kiếm sản phẩm...', pl: 'Szukaj produktów...' },
  pim_stock: { ko: '재고', en: 'Stock', zh: '库存', ja: '在庫', ru: 'Запас', hi: 'स्टॉक', ar: 'المخزون', es: 'Stock', 'pt-BR': 'Estoque', id: 'Stok', af: 'Voorraad', vi: 'Kho', pl: 'Zapasy' },
  pim_price: { ko: '가격', en: 'Price', zh: '价格', ja: '価格', ru: 'Цена', hi: 'कीमत', ar: 'السعر', es: 'Precio', 'pt-BR': 'Preço', id: 'Harga', af: 'Prys', vi: 'Giá', pl: 'Cena' },
  pim_status: { ko: '상태', en: 'Status', zh: '状态', ja: 'ステータス', ru: 'Статус', hi: 'स्थिति', ar: 'الحالة', es: 'Estado', 'pt-BR': 'Status', id: 'Status', af: 'Status', vi: 'Trạng thái', pl: 'Status' },
  pim_active: { ko: '활성', en: 'Active', zh: '激活', ja: 'アクティブ', ru: 'Активен', hi: 'सक्रिय', ar: 'نشط', es: 'Activo', 'pt-BR': 'Ativo', id: 'Aktif', af: 'Aktief', vi: 'Hoạt động', pl: 'Aktywny' },
  pim_draft: { ko: '초안', en: 'Draft', zh: '草稿', ja: '下書き', ru: 'Черновик', hi: 'ड्राफ्ट', ar: 'مسودة', es: 'Borrador', 'pt-BR': 'Rascunho', id: 'Draf', af: 'Konsep', vi: 'Bản nháp', pl: 'Szkic' },

  oms_search: { ko: '주문 검색...', en: 'Search orders...', zh: '搜索订单...', ja: '注文を検索...', ru: 'Поиск заказов...', hi: 'आदेश खोजें...', ar: 'بحث عن الطلبات...', es: 'Buscar pedidos...', 'pt-BR': 'Pesquisar pedidos...', id: 'Cari pesanan...', af: 'Soek bestellings...', vi: 'Tìm kiếm đơn hàng...', pl: 'Szukaj zamówień...' },
  oms_order_id: { ko: '주문 ID', en: 'Order ID', zh: '订单 ID', ja: '注文ID', ru: 'ID заказа', hi: 'आदेश आईडी', ar: 'رقم الطلب', es: 'ID de Pedido', 'pt-BR': 'ID do Pedido', id: 'ID Pesanan', af: 'Bestelling ID', vi: 'ID đơn hàng', pl: 'ID Zamówienia' },
  oms_customer: { ko: '고객', en: 'Customer', zh: '客户', ja: '顧客', ru: 'Клиент', hi: 'ग्राहक', ar: 'العميل', es: 'Cliente', 'pt-BR': 'Cliente', id: 'Pelanggan', af: 'Kliënt', vi: 'Khách hàng', pl: 'Klient' },
  oms_total: { ko: '총액', en: 'Total', zh: '总计', ja: '合計', ru: 'Итого', hi: 'कुल', ar: 'الإجمالي', es: 'Total', 'pt-BR': 'Total', id: 'Total', af: 'Totaal', vi: 'Tổng cộng', pl: 'Suma' },
  oms_date: { ko: '날짜', en: 'Date', zh: '日期', ja: '日付', ru: 'Дата', hi: 'तारीख', ar: 'التاريخ', es: 'Fecha', 'pt-BR': 'Data', id: 'Tanggal', af: 'Datum', vi: 'Ngày', pl: 'Data' },

  chat_placeholder: { ko: '메시지를 입력하세요...', en: 'Type a message...', zh: '输入消息...', ja: 'メッセージを入力...', ru: 'Введите сообщение...', hi: 'संदेश टाइप करें...', ar: 'اكتب رسالة...', es: 'Escribe un mensaje...', 'pt-BR': 'Digite uma mensagem...', id: 'Ketik pesan...', af: 'Tik \'n boodskap...', vi: 'Nhập tin nhắn...', pl: 'Wpisz wiadomość...' },
  chat_send: { ko: '전송', en: 'Send', zh: '发送', ja: '送信', ru: 'Отправить', hi: 'भेजें', ar: 'إرسال', es: 'Enviar', 'pt-BR': 'Enviar', id: 'Kirim', af: 'Stuur', vi: 'Gửi', pl: 'Wyślij' },
  chat_call: { ko: '음성 통화', en: 'Voice Call', zh: '语音通话', ja: '音声通話', ru: 'Голосовой звонок', hi: 'वॉयस कॉल', ar: 'مكالمة صوتية', es: 'Llamada de Voz', 'pt-BR': 'Chamada de Voz', id: 'Panggilan Suara', af: 'Stemoproep', vi: 'Cuộc gọi thoại', pl: 'Połączenie Głosowe' },
  chat_video: { ko: '영상 통화', en: 'Video Call', zh: '视频通话', ja: 'ビデオ通화', ru: 'Видеозвонок', hi: 'वीडियो कॉल', ar: 'مكالمة فيديو', es: 'Videollamada', 'pt-BR': 'Videollamada', id: 'Panggilan Video', af: 'Video-oproep', vi: 'Cuộc gọi video', pl: 'Połączenie Wideo' },

  faq_title: { ko: '자주 묻는 질문', en: 'FAQ AI', zh: '常见问题', ja: 'よくある質問', ru: 'Часто задаваемые вопросы', hi: 'सामान्य प्रश्न', ar: 'الأسئلة الشائعة', es: 'Preguntas Frecuentes', 'pt-BR': 'Perguntas Frequentes', id: 'FAQ', af: 'FAQ', vi: 'Câu hỏi thường gặp', pl: 'FAQ' },
  faq_search_placeholder: { ko: '질문 검색...', en: 'Search questions...', zh: '搜索问题...', ja: '質問を検索...', ru: 'Поиск вопросов...', hi: 'प्रश्न खोजें...', ar: 'بحث عن الأسئلة...', es: 'Buscar preguntas...', 'pt-BR': 'Pesquisar perguntas...', id: 'Cari pertanyaan...', af: 'Soek vrae...', vi: 'Tìm kiếm câu hỏi...', pl: 'Szukaj pytań...' },
  faq_contact_support: { ko: '고객 지원 문의', en: 'Contact Support', zh: '联系支持', ja: 'サポートに連絡', ru: 'Связаться с поддержкой', hi: 'सहायता से संपर्क करें', ar: 'اتصل بالدعم', es: 'Contactar Soporte', 'pt-BR': 'Contatar Suporte', id: 'Hubungi Dukungan', af: 'Kontak Ondersteuning', vi: 'Liên hệ hỗ trợ', pl: 'Skontaktuj się z Pomocą' },
  faq_powered_by: { ko: 'AI 엔진 제공', en: 'Powered by AI Engine', zh: '由 AI 引擎提供支持', ja: 'AIエンジン搭載', ru: 'На базе AI Engine', hi: 'AI इंजन द्वारा संचालित', ar: 'مدعوم من محرك الذكاء الاصطناعي', es: 'Desarrollado por AI Engine', 'pt-BR': 'Desenvolvido por AI Engine', id: 'Didukung oleh AI Engine', af: 'Aangedryf deur AI Engine', vi: 'Được cung cấp bởi AI Engine', pl: 'Zasilane przez Silnik AI' },

  dash_welcome: { ko: '다시 오신 것을 환영합니다. 오늘의 현황입니다.', en: "Welcome back, here's what's happening today.", zh: '欢迎回来，这是今天的动态。', ja: 'おかえ리なさい、本日の状況です。', ru: 'С возвращением, вот что происходит сегодня.', hi: 'वापसी पर स्वागत है, यहाँ आज क्या हो रहा है।', ar: 'مرحبًا بعودتك، إليك ما يحدث اليوم.', es: 'Bienvenido de nuevo, esto es lo que está pasando hoy.', 'pt-BR': 'Bem-vindo de volta, aqui está o que está acontecendo hoje.', id: 'Selamat datang kembali, inilah yang terjadi hari ini.', af: 'Welkom terug, hier is wat vandag gebeur.', vi: 'Chào mừng trở lại, đây là những gì đang diễn ra hôm nay.', pl: 'Witaj z powrotem, oto co się dzisiaj dzieje.' },
  dash_download: { ko: '보고서 다운로드', en: 'Download Report', zh: '下载报告', ja: 'レポートをダウンロード', ru: 'Скачать отчет', hi: 'रिपोर्ट डाउनलोड करें', ar: 'تحميل التقرير', es: 'Descargar Informe', 'pt-BR': 'Baixar Relatório', id: 'Unduh Laporan', af: 'Laai Verslag af', vi: 'Tải báo cáo', pl: 'Pobierz Raport' },
  dash_sync: { ko: '모든 마켓 동기화', en: 'Sync All Markets', zh: '同步所有市场', ja: 'すべてのマーケットを同期', ru: 'Синхронизировать все рынки', hi: 'सभी बाजारों को सिंक करें', ar: 'مزامنة جميع الأسواق', es: 'Sincronizar Todos los Mercados', 'pt-BR': 'Sincronizar Todos os Mercados', id: 'Sinkronkan Semua Pasar', af: 'Sinkroniseer Alle Markte', vi: 'Đồng bộ tất cả thị trường', pl: 'Synchronizuj Wszystkie Rynki' },
  dash_total_sales: { ko: '총 매출', en: 'Total Sales', zh: '总销售额', ja: '総売上', ru: 'Общие продажи', hi: 'कुल बिक्री', ar: 'إجمالي المبيعات', es: 'Ventas Totales', 'pt-BR': 'Vendas Totais', id: 'Total Penjualan', af: 'Totale Verkope', vi: 'Tổng doanh thu', pl: 'Całkowita Sprzedaż' },
  dash_new_orders: { ko: '신규 주문', en: 'New Orders', zh: '新订单', ja: '新規注文', ru: 'Новые заказы', hi: 'नए आदेश', ar: 'طلبات جديدة', es: 'Nuevos Pedidos', 'pt-BR': 'Novos Pedidos', id: 'Pesanan Baru', af: 'Nuwe Bestellings', vi: 'Đơn hàng mới', pl: 'Nowe Zamówienia' },
  dash_total_stock: { ko: '총 재고', en: 'Total Stock', zh: '总库存', ja: '総在庫', ru: 'Общий запас', hi: 'कुल स्टॉक', ar: 'إجمالي المخزون', es: 'Stock Total', 'pt-BR': 'Estoque Total', id: 'Total Stok', af: 'Totale Voorraad', vi: 'Tổng kho', pl: 'Całkowity Zapasy' },
  dash_automation_rate: { ko: '자동화율', en: 'Automation Rate', zh: '自动化率', ja: '自動化率', ru: 'Уровень автоматизации', hi: 'स्वचालन दर', ar: 'معدل الأتمتة', es: 'Tasa de Automatización', 'pt-BR': 'Taxa de Automação', id: 'Tingkat Otomatisasi', af: 'Outomatisering Koers', vi: 'Tỷ lệ tự động hóa', pl: 'Wskaźnik Automatyzacji' },
  dash_sales_overview: { ko: '매출 개요', en: 'Sales Overview', zh: '销售概览', ja: '売上概要', ru: 'Обзор продаж', hi: 'बिक्री अवलोकन', ar: 'نظرة عامة على المبيعات', es: 'Resumen de Ventas', 'pt-BR': 'Visão Geral de Vendas', id: 'Ikhtisar Penjualan', af: 'Verkope Oorsig', vi: 'Tổng quan doanh thu', pl: 'Przegląd Sprzedaży' },
  dash_last_7_days: { ko: '최근 7일', en: 'Last 7 Days', zh: '最近7天', ja: '過去7日間', ru: 'Последние 7 дней', hi: 'पिछले 7 दिन', ar: 'آخر 7 أيام', es: 'Últimos 7 Días', 'pt-BR': 'Últimos 7 Dias', id: '7 Hari Terakhir', af: 'Laaste 7 Dae', vi: '7 ngày qua', pl: 'Ostatnie 7 Dni' },
  dash_recent_orders: { ko: '최근 주문', en: 'Recent Orders', zh: '最近订单', ja: '最近の注文', ru: 'Последние заказы', hi: 'हाल के आदेश', ar: 'الطلبات الأخيرة', es: 'Pedidos Recientes', 'pt-BR': 'Pedidos Recientes', id: 'Pesanan Terbaru', af: 'Onlangse Bestellings', vi: 'Đơn hàng gần đây', pl: 'Ostatnie Zamówienia' },
  dash_view_all: { ko: '모든 주문 보기', en: 'View All Orders', zh: '查看所有订单', ja: 'すべての注文を表示', ru: 'Посмотреть все заказы', hi: 'सभी आदेश देखें', ar: 'عرض جميع الطلبات', es: 'Ver Todos los Pedidos', 'pt-BR': 'Ver Todos os Pedidos', id: 'Lihat Semua Pesanan', af: 'Sien Alle Bestellings', vi: 'Xem tất cả đơn hàng', pl: 'Zobacz Wszystkie Zamówienia' },
  dash_paid: { ko: '결제완료', en: 'Paid', zh: '已付款', ja: '支払い済み', ru: 'Оплачено', hi: 'भुगतान किया गया', ar: 'مدفوع', es: 'Pagado', 'pt-BR': 'Pago', id: 'Dibayar', af: 'Betaal', vi: 'Đã thanh toán', pl: 'Opłacone' },
  dash_shipped: { ko: '배송중', en: 'Shipped', zh: '已发货', ja: '発送済み', ru: 'Отправлено', hi: 'भेज दिया गया', ar: 'تم الشحن', es: 'Enviado', 'pt-BR': 'Enviado', id: 'Dikirim', af: 'Verskeep', vi: 'Đang giao', pl: 'Wysłane' },
  dash_cancelled: { ko: '취소됨', en: 'Cancelled', zh: '已取消', ja: 'キャンセル済み', ru: 'Отменено', hi: 'रद्द कर दिया गया', ar: 'ملغى', es: 'Cancelado', 'pt-BR': 'Cancelado', id: 'Dibatalkan', af: 'Gekanselleer', vi: 'Đã hủy', pl: 'Anulowane' },
  
  header_live: { ko: '라이브', en: 'Live', zh: '直播', ja: 'ライブ', ru: 'Прямой эфир', hi: '라이브', ar: 'مباشر', es: 'En Vivo', 'pt-BR': 'Ao Vivo', id: 'Langsung', af: 'Regstreeks', vi: 'Trực tiếp', pl: 'Na Żywo' },

  growth_title: { ko: '성장 엔진', en: 'Growth Engine', zh: '增长引擎', ja: '成長エンジン', ru: 'Двигатель роста', hi: 'ग्रोथ इंजन', ar: 'محرك النمو', es: 'Motor de Crecimiento', 'pt-BR': 'Motor de Crescimento', id: 'Mesin Pertumbuhan', af: 'Growth Engine', vi: 'Động cơ tăng trưởng', pl: 'Silnik Wzrostu' },
  growth_desc: { ko: '완전 자동화된 이커머스 성장 파이프라인.', en: 'Fully automated e-commerce growth pipeline.', zh: '全自动电子商务增长管道。', ja: '完全に自動化された e コマース成長パイプライン。', ru: 'Полностью автоматизированный конвейер роста электронной коммерции.', hi: 'पूरी तरह से स्वचालित ई-कॉमर्स विकास पाइपलाइन।', ar: 'خط أنابيب نمو التجارة الإلكترونية المؤتمت بالكامل.', es: 'Canal de crecimiento de comercio electrónico totalmente automatizado.', 'pt-BR': 'Pipeline de crescimento de e-commerce totalmente automatizado.', id: 'Pipa pertumbuhan e-commerce yang sepenuhnya otomatis.', af: 'Volledig outomatiese e-handel groei pyplyn.', vi: 'Đường ống tăng trưởng thương mại điện tử hoàn toàn tự động.', pl: 'W pełni zautomatyzowany rurociąg wzrostu e-commerce.' },
  growth_run_all: { ko: '전체 파이프라인 실행', en: 'Run Full Pipeline', zh: '运行完整管道', ja: 'フルパイプラインを実行', ru: 'Запустить весь конвейер', hi: 'पूर्ण पाइपलाइन चलाएँ', ar: 'تشغيل خط الأنابيب الكامل', es: 'Ejecutar Canal Completo', 'pt-BR': 'Executar Pipeline Completo', id: 'Jalankan Pipa Penuh', af: 'Loop Volledige Pyplyn', vi: 'Chạy toàn bộ đường ống', pl: 'Uruchom Pełny Rurociąg' },
  growth_execute: { ko: '지금 실행', en: 'Execute Now', zh: '立即执行', ja: '今すぐ実行', ru: 'Выполнить сейчас', hi: 'अभी निष्पादित करें', ar: 'تنفيذ الآن', es: 'Ejecutar Ahora', 'pt-BR': 'Executar Agora', id: 'Eksekusi Sekarang', af: 'Voer Nou Uit', vi: 'Thực thi ngay', pl: 'Wykonaj Teraz' },
  growth_running: { ko: '실행 중...', en: 'Running...', zh: '运行中...', ja: '运行中...', ru: 'Запуск...', hi: 'चल रहा है...', ar: 'جاري التشغيل...', es: 'Ejecutando...', 'pt-BR': 'Executando...', id: 'Berjalan...', af: 'Loop tans...', vi: 'Đang chạy...', pl: 'Uruchamianie...' },
  growth_ai_engine: { ko: 'AI 비즈니스 엔진', en: 'AI Business Engine', zh: 'AI 业务引擎', ja: 'AIビジネスエンジン', ru: 'Бизнес-двигатель ИИ', hi: 'AI बिजनेस इंजन', ar: 'محرك أعمال الذكاء الاصطناعي', es: 'Motor de Negocios IA', 'pt-BR': 'Motor de Negócios IA', id: 'Mesin Bisnis AI', af: 'AI Besigheidsenjin', vi: 'Động cơ kinh doanh AI', pl: 'Silnik Biznesowy AI' },
  growth_ai_driven: { ko: 'AI 기반 성장', en: 'AI-Driven Growth', zh: 'AI 驱动的增长', ja: 'AI主導의 성장', ru: 'Рост на базе ИИ', hi: 'AI-संचालित विकास', ar: 'النمو المدفوع بالذكاء الاصطناعي', es: 'Crecimiento Impulsado por IA', 'pt-BR': 'Crescimento Impulsionado por IA', id: 'Pertumbuhan Berbasis AI', af: 'AI-gedrewe Groei', vi: 'Tăng trưởng do AI thúc đẩy', pl: 'Wzrost Napędzany przez AI' },
  growth_ai_desc: { ko: '고급 AI를 활용하여 일반 도매 제품을 고수익 글로벌 브랜드로 전환하십시오.', en: 'Leverage advanced AI to transform generic wholesale products into high-margin global brands.', zh: '利用先进的 AI 将普通批发产品转化为高利润的全球品牌。', ja: '高度な AI を活用して、一般的な卸売製品を高利益のグローバル ブランドに変革します。', ru: 'Используйте передовой ИИ для превращения обычных оптовых товаров в высокодоходные мировые бренды.', hi: 'जेनेरिक थोक उत्पादों को उच्च-मार्जिन वाले वैश्विक ब्रांडों में बदलने के लिए उन्नत AI का लाभ उठाएं।', ar: 'استفد من الذكاء الاصطناعي المتقدم لتحويل منتجات الجملة العامة إلى علامات تجارية عالمية عالية الهامش.', es: 'Aproveche la IA avanzada para transformar productos mayoristas genéricos en marcas globales de alto margen.', 'pt-BR': 'Aproveite a IA avançada para transformar produtos de atacado genéricos em marcas globais de alta margem.', id: 'Manfaatkan AI canggih untuk mengubah produk grosir generik menjadi merek global bermargin tinggi.', af: 'Gebruik gevorderde AI om generiese groothandelprodukte in hoë-marge globale handelsmerke te omskep.', vi: 'Tận dụng AI tiên tiến để biến các sản phẩm bán buôn thông thường thành các thương hiệu toàn cầu có tỷ suất lợi nhuận cao.', pl: 'Wykorzystaj zaawansowaną sztuczną inteligencję, aby przekształcić generyczne produkty hurtowe w wysokomarżowe globalne marki.' },
};

export const faqs: { question: Record<Language, string>; answer: Record<Language, string> }[] = [
  {
    question: { ko: '이 플랫폼은 무엇인가요?', en: 'What is this platform?', zh: '这个平台是什么？', ja: 'このプラットフォームは何ですか？', ru: 'Что это за платформа?', hi: 'यह प्लेटफॉर्म क्या है?', ar: 'ما هي هذه المنصة؟', es: '¿Qué es esta plataforma?', 'pt-BR': 'O que é esta plataforma?', id: 'Apa platform ini?', af: 'Wat is hierdie platform?', vi: 'Nền tảng này là gì?', pl: 'Co to za platforma?' },
    answer: { ko: 'AI 기반 글로벌 자동 판매 플랫폼입니다.', en: 'It is an AI-based global automated sales platform.', zh: '这是一个基于人工智能的全球自动销售平台。', ja: 'AIベースのグローバル自動販売プラットフォームです。', ru: 'Это глобальная платформа автоматизированных продаж на базе ИИ.', hi: 'यह एक AI-आधारित वैश्विक स्वचालित बिक्री मंच है।', ar: 'إنها منصة مبيعات عالمية مؤتمتة قائمة على الذكاء الاصطناعي.', es: 'Es una plataforma de ventas automatizada global basada en IA.', 'pt-BR': 'É uma plataforma de vendas automatizada global baseada em IA.', id: 'Ini adalah platform penjualan otomatis global berbasis AI.', af: 'Dit is \'n AI-gebaseerde globale outomatiese verkope platform.', vi: 'Đây là nền tảng bán hàng tự động toàn cầu dựa trên AI.', pl: 'To globalna zautomatyzowana platforma sprzedaży oparta na sztucznej inteligencji.' }
  },
  {
    question: { ko: '무료인가요?', en: 'Is it free?', zh: '免费吗？', ja: '無料ですか？', ru: 'Это бесплатно?', hi: 'क्या यह मुफ़्त है?', ar: 'هل هو مجاني؟', es: '¿Es gratis?', 'pt-BR': 'É grátis?', id: 'Apakah ini gratis?', af: 'Is dit gratis?', vi: 'Nó có miễn phí không?', pl: 'Czy to jest darmowe?' },
    answer: { ko: '네, 로그인 없이 모든 기능 사용 가능합니다.', en: 'Yes, all features are available without login.', zh: '是的，所有功能无需登录即可使用。', ja: 'はい、ログインなしですべての機能利用可能합니다.', ru: 'Да, все функции доступны без входа в систему.', hi: 'हाँ, सभी सुविधाएँ बिना लॉगिन के उपलब्ध हैं।', ar: 'نعم، جميع الميزات متاحة بدون تسجيل الدخول.', es: 'Sí, todas las funciones están disponibles sin iniciar sesión.', 'pt-BR': 'Sim, todos os recursos estão disponíveis sem login.', id: 'Ya, semua fitur tersedia tanpa login.', af: 'Ja, alle funksies is beskikbaar sonder aanteken.', vi: 'Có, tất cả các tính năng đều có sẵn mà không cần đăng nhập.', pl: 'Tak, wszystkie funkcje są dostępne bez logowania.' }
  },
  {
    question: { ko: '어떤 마켓 연동되나요?', en: 'Which markets are linked?', zh: '关联了哪些市场？', ja: 'どのマーケットが連携されていますか？', ru: 'Какие рынки связаны?', hi: 'कौन से बाजार जुड़े हुए हैं?', ar: 'ما هي الأسواق المرتبطة؟', es: '¿Qué mercados están vinculados?', 'pt-BR': 'Quais mercados estão vinculados?', id: 'Pasar mana yang tertaut?', af: 'Watter markte is gekoppel?', vi: 'Những thị trường nào được liên kết?', pl: 'Które rynki są powiązane?' },
    answer: { ko: 'Amazon, Shopee, TikTok Shop 연동됩니다.', en: 'Amazon, Shopee, TikTok Shop are linked.', zh: '亚马逊、Shopee、TikTok Shop 已关联。', ja: 'Amazon、Shopee、TikTok Shopが連携されています。', ru: 'Amazon, Shopee, TikTok Shop связаны.', hi: 'Amazon, Shopee, TikTok Shop जुड़े हुए हैं।', ar: 'تم ربط Amazon و Shopee و TikTok Shop.', es: 'Amazon, Shopee, TikTok Shop están vinculados.', 'pt-BR': 'Amazon, Shopee, TikTok Shop estão vinculados.', id: 'Amazon, Shopee, TikTok Shop tertaut.', af: 'Amazon, Shopee, TikTok Shop is gekoppel.', vi: 'Amazon, Shopee, TikTok Shop được liên kết.', pl: 'Amazon, Shopee, TikTok Shop są powiązane.' }
  },
  {
    question: { ko: '자동 상품 등록 되나요?', en: 'Is automatic product registration possible?', zh: '可以自动注册产品吗？', ja: '自動商品登録は可能ですか？', ru: 'Возможна ли автоматическая регистрация товара?', hi: 'क्या स्वचालित उत्पाद पंजीकरण संभव है?', ar: 'هل يمكن تسجيل المنتج تلقائيا؟', es: '¿Es posible el registro automático de productos?', 'pt-BR': 'O registro automático de produtos é possível?', id: 'Apakah pendaftaran produk otomatis dimungkinkan?', af: 'Is outomatiese produkregistrasie moontlik?', vi: 'Có thể đăng ký sản phẩm tự động không?', pl: 'Czy możliwa jest automatyczna rejestracja produktu?' },
    answer: { ko: '1688 기반 자동 등록 가능합니다.', en: 'Automatic registration based on 1688 is possible.', zh: '可以基于 1688 进行自动注册。', ja: '1688ベースの自動登録が可能です。', ru: 'Возможна автоматическая регистрация на базе 1688.', hi: '1688 के आधार पर स्वचालित पंजीकरण संभव है।', ar: 'التسجيل التلقائي بناءً على 1688 ممكن.', es: 'El registro automático basado en 1688 es posible.', 'pt-BR': 'O registro automático baseado em 1688 é possível.', id: 'Pendaftaran otomatis berdasarkan 1688 dimungkinkan.', af: 'Outomatiese registrasie gebaseer op 1688 is moontlik.', vi: 'Có thể đăng ký tự động dựa trên 1688.', pl: 'Możliwa jest automatyczna rejestracja na podstawie 1688.' }
  },
  {
    question: { ko: '번역 기능 있나요?', en: 'Is there a translation function?', zh: '有翻译功能吗？', ja: '翻訳機能はありますか？', ru: 'Есть ли функция перевода?', hi: 'क्या कोई अनुवाद कार्य है?', ar: 'هل هناك وظيفة الترجمة؟', es: '¿Hay una función de traducción?', 'pt-BR': 'Existe uma função de traducción?', id: 'Apakah ada fungsi terjemahan?', af: 'Is daar \'n vertaalfunksie?', vi: 'Có chức năng dịch thuật không?', pl: 'Czy jest funkcja tłumaczenia?' },
    answer: { ko: '13개 언어 자동 번역 지원합니다.', en: 'Supports automatic translation of 13 languages.', zh: '支持 13 种语言的自动翻译。', ja: '13言語の自動翻訳をサポートしています。', ru: 'Поддерживает автоматический перевод на 13 языков.', hi: '13 भाषाओं के स्वचालित अनुवाद का समर्थन करता है।', ar: 'يدعم الترجمة الآلية لـ 13 لغة.', es: 'Admite la traducción automática de 13 idiomas.', 'pt-BR': 'Suporta tradução automática de 13 idiomas.', id: 'Mendukung terjemahan otomatis 13 bahasa.', af: 'Ondersteun outomatiese vertaling van 13 tale.', vi: 'Hỗ trợ dịch tự động 13 ngôn ngữ.', pl: 'Obsługuje automatyczne tłumaczenie 13 języków.' }
  },
  {
    question: { ko: '영상 생성 되나요?', en: 'Can videos be generated?', zh: '可以生成视频吗？', ja: '動画の生成は可能ですか？', ru: 'Можно ли создавать видео?', hi: 'क्या वीडियो जेनरेट किए जा सकते हैं?', ar: 'هل يمكن إنشاء مقاطع فيديو؟', es: '¿Se pueden generar videos?', 'pt-BR': 'Os vídeos podem ser gerados?', id: 'Bisakah video dibuat?', af: 'Kan video\'s gegenereer word?', vi: 'Video có thể được tạo ra không?', pl: 'Czy można generować filmy?' },
    answer: { ko: 'TikTok용 영상 자동 생성됩니다.', en: 'Videos for TikTok are automatically generated.', zh: '自动生成 TikTok 视频。', ja: 'TikTok用の動画が自動生成されます。', ru: 'Видео для TikTok создаются автоматически.', hi: 'TikTok के लिए वीडियो स्वचालित रूप से जेनरेट किए जाते हैं।', ar: 'يتم إنشاء مقاطع فيديو لـ TikTok تلقائيًا.', es: 'Los videos para TikTok se generan automáticamente.', 'pt-BR': 'Os vídeos para o TikTok são gerados automaticamente.', id: 'Video untuk TikTok dibuat secara otomatis.', af: 'Video\'s vir TikTok word outomaties gegenereer.', vi: 'Video cho TikTok được tạo tự động.', pl: 'Filmy dla TikTok są generowane automatycznie.' }
  },
  {
    question: { ko: '드랍쉬핑 가능한가요?', en: 'Is dropshipping possible?', zh: '可以代发货吗？', ja: 'ドロップシッピングは可能ですか？', ru: 'Возможен ли дропшиппинг?', hi: 'क्या ड्रॉपशिपिंग संभव है?', ar: 'هل الدروبشيبينغ ممكن؟', es: '¿Es posible el dropshipping?', 'pt-BR': 'O dropshipping é possível?', id: 'Apakah dropshipping dimungkinkan?', af: 'Is dropshipping moontlik?', vi: 'Có thể dropshipping không?', pl: 'Czy dropshipping jest możliwy?' },
    answer: { ko: '자동 발주 기반 드랍쉬핑 가능합니다.', en: 'Dropshipping based on automatic ordering is possible.', zh: '可以基于自动下单进行代发货。', ja: '自動発注ベースのドロップシッピングが可能です。', ru: 'Возможен дропшиппинг на основе автоматического заказа.', hi: 'स्वचालित ऑर्डरिंग के आधार पर ड्रॉपशिपिंग संभव है।', ar: 'الدروبشيبينغ على أساس الطلب التلقائي ممكن.', es: 'El dropshipping basado en pedidos automáticos es posible.', 'pt-BR': 'O dropshipping baseado em pedidos automáticos es possível.', id: 'Dropshipping berdasarkan pemesanan otomatis dimungkinkan.', af: 'Dropshipping gebaseer op outomatiese bestelling is moontlik.', vi: 'Có thể dropshipping dựa trên đặt hàng tự động.', pl: 'Możliwy jest dropshipping oparty na automatycznym zamawianiu.' }
  },
  {
    question: { ko: '재고 관리 되나요?', en: 'Is inventory management possible?', zh: '可以관리库存吗？', ja: '在庫管理は可能ですか？', ru: 'Возможно ли управление запасами?', hi: 'क्या इन्वेंट्री प्रबंधन संभव है?', ar: 'هل إدارة المخزون ممكنة؟', es: '¿Es posible la gestión de inventario?', 'pt-BR': 'A gestão de inventário é possível?', id: 'Apakah manajemen inventaris dimungkinkan?', af: 'Is voorraadbestuur moontlik?', vi: 'Có thể quản lý kho không?', pl: 'Czy możliwe jest zarządzanie zapasami?' },
    answer: { ko: '실시간 재고 동기화됩니다.', en: 'Real-time inventory synchronization.', zh: '实时库存同步。', ja: 'リアルタイムの在庫同期。', ru: 'Синхронизация запасов в реальном времени.', hi: 'वास्तविक समय सूची सिंक्रनाइज़ेशन।', ar: 'مزامنة المخزون في الوقت الحقيقي.', es: 'Sincronización de inventario en tiempo real.', 'pt-BR': 'Sincronização de estoque em tempo real.', id: 'Sinkronisasi inventaris waktu nyata.', af: 'Intydse voorraad sinkronisasie.', vi: 'Đồng bộ kho thời gian thực.', pl: 'Synchronizacja zapasów w czasie rzeczywistym.' }
  },
  {
    question: { ko: '가격 자동 조정 되나요?', en: 'Is there automatic price adjustment?', zh: '有自动价格调整吗？', ja: '自動価格調整はありますか？', ru: 'Есть ли автоматическая корректировка цен?', hi: 'क्या स्वचालित मूल्य समायोजन है?', ar: 'هل هناك تعديل تلقائي للسعر؟', es: '¿Hay ajuste automático de precios?', 'pt-BR': 'Existe ajuste automático de precios?', id: 'Apakah ada penyesuaian harga otomatis?', af: 'Is daar outomatiese prys aanpassing?', vi: 'Có điều chỉnh giá tự động không?', pl: 'Czy jest automatyczna korekta ceny?' },
    answer: { ko: '경쟁사 기반 자동 조정됩니다.', en: 'Automatic adjustment based on competitors.', zh: '基于竞争对手的自动调整。', ja: '競合他社に基づいた自動調整。', ru: 'Автоматическая корректировка на основе конкурентов.', hi: 'प्रतियोगियों के आधार पर स्वचालित समायोजन।', ar: 'تعديل تلقائي بناءً على المنافسين.', es: 'Ajuste automático basado en competidores.', 'pt-BR': 'Ajuste automático baseado em concorrentes.', id: 'Penyesuaian otomatis berdasarkan pesaing.', af: 'Outomatiese aanpassing gebaseer op mededingers.', vi: 'Tự động điều chỉnh dựa trên đối thủ cạnh tranh.', pl: 'Automatyczna korekta na podstawie konkurencji.' }
  },
  {
    question: { ko: '광고 자동화 되나요?', en: 'Is advertising automated?', zh: '广告自动化吗？', ja: '広告は自動化されていますか？', ru: 'Автоматизирована ли реклама?', hi: 'क्या विज्ञापन स्वचालित है?', ar: 'هل الإعلان مؤتمت؟', es: '¿Está automatizada la publicidad?', 'pt-BR': 'A publicidade é automatizada?', id: 'Apakah iklan otomatis?', af: 'Is advertensies outomaties?', vi: 'Quảng cáo có tự động không?', pl: 'Czy reklama jest zautomatyzowana?' },
    answer: { ko: 'Amazon PPC 자동 실행됩니다.', en: 'Amazon PPC runs automatically.', zh: '亚马逊 PPC 自动运行。', ja: 'Amazon PPCが自動的に実行されます。', ru: 'Amazon PPC запускается автоматически.', hi: 'Amazon PPC स्वचालित रूप से चलता है।', ar: 'يعمل Amazon PPC تلقائيًا.', es: 'Amazon PPC se ejecuta automáticamente.', 'pt-BR': 'O Amazon PPC é executado automaticamente.', id: 'Amazon PPC berjalan secara otomatis.', af: 'Amazon PPC loop outomaties.', vi: 'Amazon PPC chạy tự động.', pl: 'Amazon PPC działa automatycznie.' }
  },
];
